### ISSUE TITLE
[Crash]: Modpack stopped running after the update Aether: Redux v2.0.14 for (Neo)Forge 1.20.1

### ISSUE THREAD

**Issue by Tapacywka** [Zepalesque/Aether-Redux-Issue-Tracker#114]
### Minecraft Version

1.20.1

### Mod Version

2.0.14

### Forge/Neoforge Version

NeoForge 47.1.105

### What happened?

Because you built AeroBlender and Geckolib directly into Aether: Redux itself, the modpack stopped running. Even manually deleting AeroBlender and Geckolib from the mods folder, which are no longer needed, does not help.

### What was the expected result?

The client should start up.

### Steps to Reproduce

Install the modpack from this link via PrismLauncher or any other that supports .mrpack format (I own it).
https://drive.google.com/file/d/1DU4kKnO19S8PR9XBRVtb5AnHoNzvThSC/view?usp=sharing

### Crash Report (if applicable)

https://mclo.gs/5zFkPc8

### Additional Context/Information

The modpack works fine with the previous version of Aether: Redux, where there is no built-in AeroBlender and Geckolib. You can check it yourself by replacing the current version of Aether: Redux with the previous version.

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zedrimar** [comment]
Can confirm on my end too.

**Comment by Zepalesque** [comment]
based on the crash, this doesn't appear to be an aeroblender-related issue, but is actually a problem with a different thing done in this update, but I'll fix that and release a new version pretty soon (2.0.14b)

**Comment by Zepalesque** [comment]
*should* now be fixed in 2.0.14b

**Comment by Tapacywka** [comment]
https://mclo.gs/2TdoXDz
Should I manually uninstall the previously installed AeroBlender and Geckolib?
Because it's still crashing.

**Comment by Tapacywka** [comment]
Yes, it looks like the modpack is running after they gone.
But I need the 4.4.4 version of Geckolib for NeoForge, what should I do in this case?

**Comment by Zepalesque** [comment]
hmm, yeah I think I'm going to have to make a 2.0.14c, because it seems I broke something lol

**Comment by Zedrimar** [comment]
There was also this crash, not sure if it's related, but it seems different than the log posted in the previous comment. https://pastebin.com/PgeJszm5

**Comment by AidanWright** [comment]
> There was also this crash, not sure if it's related, but it seems different than the log posted in the previous comment. https://pastebin.com/PgeJszm5

I'm getting the same error on my install of 2.0.14b as well, regardless of AeroBlender and Geckolib being installed alongside. It seems like it's related. see: bernie-g/geckolib#170

**Comment by Veynam** [comment]
Game still crashing on startup with the latest update.

**Comment by Zepalesque** [comment]
I am aware
for the moment please use v2.0.13 instead, I will be able to fix the issue _relatively_ soon

**Comment by katubug** [comment]
Thank you for working on this! We appreciate the work you do.

**Comment by Zepalesque** [comment]
thanks! and yeah the update should be done *hopefully* sometime today, I've had a cold for a bit so I haven't been able to really work on the mod, but luckily that seems to be just about gone

**Comment by katubug** [comment]
Aww that's going around here, too. I'm sorry you're not feeling well, I
hope you recover soon!

**Comment by Zepalesque** [comment]
ok, this should now be fixed as of 2.0.15!
