### ISSUE TITLE
[Bug]: Treasure Reforging Compat doesn't properly work when Treasure Reforging is added to an existing world

### ISSUE THREAD

**Issue by VoidLeech** [Zepalesque/Aether-Redux-Issue-Tracker#123]
### Minecraft Version

1.20.1

### Mod Version

2.0.16

### Forge/Neoforge Version

Forge 47.2.0

### What happened?

I had an existing world that used Redux, before Treasure Reforging got released.
Upon adding Treasure Reforging and updating to a Redux version with compat, I checked out the template recipes and noticed these still use enchanted gravitite.
It seems the built-in compat datapack is loaded before the one from Treasure Reforging itself, preventing the built-in pack from overriding it.
Using `/datapack disable "builtin/data/gravitite_ingot"` does move the pack behind the one from Treasure Reforging, which works after a `/reload`, but this is not persistent upon leaving and rejoining the world. (And doesn't work for me as a workaround, but that isn't an issue with Redux, as I have some other mod in the existing world crashing if items are removed from a tag during `/reload` or `/datapack disable`)

### What was the expected result?

That the Treasure Reforging templates can be crafted with a gravitite ingot instead of the now unobtainable enchanted gravitite.

### Steps to Reproduce

1. Install Redux & Dependencies
2. Create World
3. Leave World
4. Install Treasure Reforging
5. Join World
6. Look up recipes for the Treasure Reforging templates.
7. Observe incorrect recipes

### Is this a compatibility issue with another mod?

Treasure Reforging 1.0.0

### Additional Context/Information

Incorrect recipe (/w Gravitite Ingot turned on)
![image](https://github.com/Zepalesque/The-Aether-Redux/assets/57987812/667c58f9-a435-43a7-a8b9-1e8c20178a90)
`/datapack list` after reproduction steps.
![image](https://github.com/Zepalesque/The-Aether-Redux/assets/57987812/42bd0bad-8592-4652-a3f9-7c4c8f87ea9e)

Reversing the order of mod installation between Treasure Reforging and Redux, the compat works as expected.
Mentioned by @Lucky-56 in #115 but no proper issue existed yet.

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it only occurs *with* Redux installed, and not without
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
hmm, I have an idea for a fix for this, which will be in 2.0.16b

**Comment by Zepalesque** [comment]
should be fixed now

**Comment by VoidLeech** [comment]
I can still reproduce this on the latest release (2.0.16c) :(

**Comment by VoidLeech** [comment]
I have since found a workaround that works for me.
Via NBTExplorer, I've gone to `level.dat > Data > DataPacks > Enabled`, and moved the "builtin/data/gravitite_ingot" string to after the "mod:aether_treasure_reforging" one. 
I imagine you could do a similar thing in code?

**Comment by Zepalesque** [comment]
ahh, yeah hmm
if that’s the issue you’d probably have to move it to the top yeah
unfortunately I don’t know if there is an easy way to do this without making customization harder
luckily, the Aether has an item tag for gravitite, I still need to switch the ingot datapack to replace that instead lol
assuming that treasure reforging uses that tag in its recipes, I should be able to fix this fairly easily as I won’t have to override the recipe at all

**Comment by Zepalesque** [comment]
ok i actually have an idea for this that is obvious in hindsight so this will be fixed in 2.0.18

**Comment by Zepalesque** [comment]
presumably i fixed this in 2.0.18? so i'll close it ig
